### PR TITLE
Fix AWS mount. Resolves #9

### LINKED ISSUE #9: Typo in the aws mount instruction
There is a typo in the aws mount instruction, would it matter that I create a separate pull request on that, since its not conflicting code to my other?

### PR DESCRIPTION
**Pull request by timrettop**

### CODE REVIEW

File: udm-le.sh [hunk 1]
```diff
@@ -45,7 +45,7 @@ done
 
 # Check for optional .aws directory, and add it to the mounts if it exists
 if [ -d "${UDM_LE_PATH}/.aws" ]; then
-        DOCKER_VOLUMES="${DOCKER_VOLUMES} -v ${UDM_LE_PATH}/aws:/home/lego/.aws/"
+        DOCKER_VOLUMES="${DOCKER_VOLUMES} -v ${UDM_LE_PATH}/.aws:/home/lego/.aws/"
```
Comment (kchristensen) [inline udm-le.sh:48]: Oops, good catch!
