### PR TITLE
fix: java not found error

### LINKED ISSUE #109: [BUG] Keystore not updating (Hotspot Portal)
**Describe the bug**
The hotspot portal has stopped updating. The old certificate generated a year ago (now expired) is shown.

**To Reproduce**
1. set `ENABLE_CAPTIVE="yes"`
2. run `udm-le.sh initial` 

**Expected behavior**
Captive WiFi portal certificate should update automatically.

**Version Information (please complete the following information):**
 - UniFi OS: 4.1.13
 - Hardware Type:  UDM

**Additional context**
The `update_keystore()` throws an error:

```
deploy_certs(): New certificate was generated, time to deploy it
update_keystore(): Importing full certificate chain bundle
/data/udm-le/udm-le.sh: line 154: java: command not found
```

### PR DESCRIPTION
**Pull request by zenopopovici**
I've submitted a fix for the `java-not-found`. Fixes #109 

You can close this if you don't want to push it but it might help others looking for a fix.

### CODE REVIEW

File: udm-le.sh [hunk 1]
```diff
@@ -183,6 +184,18 @@ install_lego() {
 	fi
 }
 
+install_java() {
+	# Check if lego exists already, do nothing
+	if [ ! -f "${JAVA_BINARY}" ] || [ "${JAVA_FORCE_INSTALL}" = true ]; then
+		echo "install_java(): Attempting java installation"
+
+		# install jre via apt
+		apt install default-jre-headless
```
Comment (kchristensen) [inline udm-le.sh:193]: I think you want this to be `apt install -y --no-install-recommends default-jre-headless` so it doesn't prompt, and so it doesn't drag in a bunch of other packages it doesn't need.

Also I think we might want to change line 189 to take into account if people don't have `ENABLE_CAPTIVE` set to `yes`, since they won't actually need java if they're not using the captive portal.

Does that make sense? I'd also ditch the else log line, that way people without ENABLE_CAPTIVE set won't be seeing a log line about java stuff when they don't even need it.

Comment (zenopopovici) [reply udm-le.sh:193]: 1. @kchristensen Yup ... obvious mistake on my side. 
2. Yep, makes sense.

Fixing in a bit.

**Comment by zenopopovici** [comment]
@kchristensen There. Feedback incorporated. :)

**Comment by kchristensen** [comment]
This looks great! Thanks for all the troubleshooting and working through this.

**Comment by zenopopovici** [comment]
You're welcome! Glad I could help!
